apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;
    events {
        worker_connections  1024;
    }
    http {
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
        # Path to access.log & error.log
        access_log /var/log/nginx/access.log  main;
        error_log /var/log/nginx/error.log  warn;
        sendfile        on;
        keepalive_timeout  65;
        gzip  on;
        upstream backend {
            # must match the target service name
            server svc-wordpress:80;
        }
        server {
            listen       80;
            location / {
                # $http_host is the host name that users seen on the browser URL
                # and it equals to `HTTP_HOST` request header.
                proxy_set_header Host $http_host;
                # You have to change this according to your setup.
                proxy_pass http://svc-wordpress;
                # Modify `Location` of 301 or 302 HTTP response, so
                # that the browser will follow the correct location.
                proxy_redirect ~^http://[^/]*/(.*) http://$http_host/$1;
            }
        }
    }
---
# kubectl create configmap nginx-conf --from-file=conf/nginx.conf --dry-run -o yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-conf
data: 
  fluent.conf: |
    <source>
      type tail
      path /logs/**/access.log
      tag nginx.access
      format nginx
    </source>
    <source>
      @type tail
      format /^(?<time>\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2}) \[(?<log_level>\w+)\] (?<pid>\d+).(?<tid>\d+): (?<message>.*)$/
      tag nginx.error
      path /logs/**/error.log
    </source>
    <match nginx.access>
      @type stdout
    </match>
    <match nginx.error>
      @type stdout
    </match>
