apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      db: mysql
  template:
    metadata:
      labels:
        db: mysql
    spec:
      containers:
        - image: mysql:latest
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: secret
          ports:
            - containerPort: 3306
              name: mysql
          # volumeMounts:
          #   - name: mysql-persistent-storage
          #     mountPath: /var/lib/mysql
      # volumes:
        # - name: mysql-persistent-storage
          # persistentVolumeClaim:
          #   claimName: mysql-hw-pv-claim
